name: triggered
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["entry"]
    types:
      - completed

jobs:
  testing-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.workflow_run.head_sha }}
          echo ${{ toJson(github) }}
    